### ISSUE TITLE
Importer failure of test class in documentation build only

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#1078]
This has been going on for weeks, and I'm not certain why it started or how to fix it - see error at end.

There's test class [here](https://github.com/ManiacalLabs/BiblioPixel/blob/master/test/bibliopixel/animation/documentation_class.py) that is used entirely for examples in the documentation.

It now fails to import _only_ during the documentation phase.  I've tried from inside a Python interpreter and it works perfectly well.  

I feel it's something to do with the fact that we don't _install_ the test files (as we shouldn't) but the PYTHONPATH does point to the root of the BiblioPixel directory so it shouldn't be an issue.

Interestingly enough a line towards the end seems to indicate that I'm somewhere loading `bibliopixel.animation.test`. I've definitely made that mistake before - it should be `bibliopixel.animation.tests` - but I can't find anywhere that this mistake is today in the codebase.

Worst case, I'll just move this one file somewhere obscure in the main hierarchy and use it from there, but I hate to do that.

    ERROR - extract-gifs - Error in project doc/tutorial/2-example-6.gif
    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 7, in imp
        return importlib.import_module(tn)
      File "/development/env/blips/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'test.bibliopixel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 7, in imp
        return importlib.import_module(tn)
      File "/development/env/blips/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'test.bibliopixel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 7, in imp
        return importlib.import_module(tn)
      File "/development/env/blips/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'test.bibliopixel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 7, in imp
        return importlib.import_module(tn)
      File "/development/env/blips/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'test.bibliopixel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 26, in _import
        return name, imp(name)
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 14, in imp
        namespace = imp('.'.join(parts))
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 14, in imp
        namespace = imp('.'.join(parts))
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 14, in imp
        namespace = imp('.'.join(parts))
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 15, in imp
        return getattr(namespace, module)
    AttributeError: module 'test' has no attribute 'bibliopixel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/env/blips/lib/python3.6/site-packages/loady/importer.py", line 7, in imp
        return importlib.import_module(tn)
      File "/development/env/blips/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'bibliopixel.animation.test'

**Comment by rec** [comment]
Ah, I've figured out where `'bibliopixel.animation.test'` comes from and it's a coincidence.  Developing.

**Comment by rec** [comment]
Got it!

Very interesting - something earlier (and new) in the `sys.path` was matching `test.` so `test.bibliopixel` didn't resolve.  Solved by inserting the root directory at the _start_ of `sys.path`.
