### ISSUE TITLE
Error when trying to use keyboard

### ISSUE THREAD

**Issue by prismofeverything** [ManiacalLabs/BiblioPixel#1156]
Whenever I try to use a keyboard control, either:

    bp monitor keyboard

or the test project that uses the keyboard:

    bp projects/21-key-control.yml

I get the following error:

```
ERROR - project_runner - 1 project failed
____________________

ERROR - project_runner - Unable to create control

No member specified in fullname = keyboard:
names = ['KEY_DOWN', 'KEY_UP', 'KeyboardEvent', 'add_abbreviation', 'add_hotkey', 'add_word_listener', 'all_modifiers', 'block_key', 'call_later', 'clear_all_hotkeys', 'clear_hotkey', 'get_hotkey_name', 'get_typed_strings', 'hook', 'hook_key', 'is_modifier', 'is_pressed', 'key_to_scan_codes', 'normalize_name', 'on_press', 'on_press_key', 'on_release', 'on_release_key', 'parse_hotkey', 'parse_hotkey_combinations', 'play', 'press', 'press_and_release', 'read_event', 'read_hotkey', 'read_key', 'record', 'register_abbreviation', 'register_hotkey', 'register_word_listener', 'release', 'remap_hotkey', 'remap_key', 'remove_abbreviation', 'remove_all_hotkeys', 'remove_hotkey', 'remove_word_listener', 'replay', 'restore_modifiers', 'restore_state', 'send', 'sided_modifiers', 'start_recording', 'stash_state', 'stop_recording', 'unblock_key', 'unhook', 'unhook_all', 'unhook_all_hotkeys', 'unhook_key', 'unregister_all_hotkeys', 'unregister_hotkey', 'unremap_hotkey', 'unremap_key', 'version', 'wait', 'write']
module_name = keyboard
matches = []


Traceback (most recent call last):
  File "/Users/rspangler/.pyenv/versions/orb/bin/bp", line 16, in <module>
    main.main()
  File "/Users/rspangler/.pyenv/versions/3.7.3/envs/orb/lib/python3.7/site-packages/bibliopixel/main/main.py", line 31, in main
    module.run(args)
  File "/Users/rspangler/.pyenv/versions/3.7.3/envs/orb/lib/python3.7/site-packages/bibliopixel/commands/run.py", line 12, in run
    project_runner.run(args)
  File "/Users/rspangler/.pyenv/versions/3.7.3/envs/orb/lib/python3.7/site-packages/bibliopixel/project/project_runner.py", line 27, in run
    projects = _get_projects(args)
  File "/Users/rspangler/.pyenv/versions/3.7.3/envs/orb/lib/python3.7/site-packages/bibliopixel/project/project_runner.py", line 199, in _get_projects
    raise ValueError('Run aborted')
ValueError: Run aborted
```

Any idea what might be going wrong?

**Comment by prismofeverything** [comment]
Specifically, it seems the real error is further down the stack but is perhaps getting obscured by the project runner? Would like to know where "No member specified" is really happening.

**Comment by kentellsw** [comment]
Just picked up my allpixel board again and I'm not seeing much love for this new version of bibliopixel.  Is it still active or should I use the older version

**Comment by adammhaile** [comment]
@kentellsw It's still supported but over on the forum: https://forum.maniacallabs.com/
