### ISSUE TITLE
Obscure errors when failing to import specific `BiblioPixelAnimation` classes.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#184]
Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
    AttributeError: 'module' object has no attribute '__path__'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/development/BiblioPixel/main.py", line 6, in <module>
        main.main()
      File "/development/BiblioPixel/bibliopixel/main/main.py", line 41, in main
        sys.exit(run(args, presets) or 0)
      File "/development/BiblioPixel/bibliopixel/main/demo.py", line 224, in run
        runnable = make_runnable(demo, args)
      File "/development/BiblioPixel/bibliopixel/main/demo.py", line 192, in make_runnable
        return project.make_runnable(**demo)
      File "/development/BiblioPixel/bibliopixel/project/project.py", line 57, in make_runnable
        return make(**apply_defaults(kwds))
      File "/development/BiblioPixel/bibliopixel/project/defaults.py", line 38, in apply_defaults
        return merge(DEFAULTS, resolve_aliases(desc))
      File "/development/BiblioPixel/bibliopixel/project/aliases.py", line 54, in resolve_aliases
        (key in result) and replace(result, key, aliases)
      File "/development/BiblioPixel/bibliopixel/project/aliases.py", line 50, in replace
        replace(animations, i, aliases)
      File "/development/BiblioPixel/bibliopixel/project/aliases.py", line 46, in replace
        typeclass = import_symbol(typename)
      File "/development/BiblioPixel/bibliopixel/project/importer.py", line 43, in import_symbol
        result = importer.import_symbol(typename, package)
      File "/development/BiblioPixel/bibliopixel/util/importer.py", line 7, in import_symbol
        return importlib.import_module(typename, package=package)
      File "/development/env/led3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2221, in _find_and_load_unlocked
    ImportError: No module named 'BiblioPixelAnimations.cube.bloom.CubeBloom'; 'BiblioPixelAnimations.cube.bloom' is not a package
    Please install the BiblioPixelAnimations library from here:

    https://github.com/ManiacalLabs/BiblioPixelAnimations

**Comment by rec** [comment]
Also - "that could also happen if, for example, they try to import the PerlinSimplex animations but don't have pynoise installed"
