### ISSUE TITLE
Using multiple drivers in a project assumes Matrix

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#378]
Try this:
```
{
    "driver": {
        "typename": "simpixel",
        "num": 100
    },
    "drivers": [
        {"port": 1337},
        {"port": 1338}
    ],
    "layout": "strip",
    "animation": "BiblioPixelAnimations.strip.Rainbows.RainbowCycle"
}
```

Fails with:
```
Traceback (most recent call last):
  File "/home/ahaile/.pyenv/bp3/bin/bp", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ahaile/misc/BP3/BiblioPixel/scripts/bp", line 15, in <module>
    main.main()
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/main/main.py", line 62, in main
    return run(args) or 0
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/main/run.py", line 22, in run
    task = common_flags.make_animation(args, desc or {})
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/main/common_flags.py", line 130, in make_animation
    return project.project_to_animation(desc, project_flags)
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/project/project.py", line 86, in project_to_animation
    driver_objects = builder.make_drivers(driver, drivers)
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/layout/multimap.py", line 20, in make_drivers
    return [self._make_driver(**d) for d in drivers]
  File "/home/ahaile/misc/BP3/BiblioPixel/bibliopixel/layout/multimap.py", line 20, in <listcomp>
    return [self._make_driver(**d) for d in drivers]
TypeError: _make_driver() missing 2 required positional arguments: 'width' and 'height'
```

If you have multiple drivers in a project it assumes you are using a matrix. Which is very wrong. Strip is valid as well. Needs to be fixed ASAP for a 3.2.1 release.

**Comment by rec** [comment]
Not a surprise.  :-D

I actually have a whole bunch of AllPixels and strip LEDs now in a box downstairs I haven't opened yet, so I can easily test this with hardware too.

**Comment by adammhaile** [comment]
Cool :)

**Comment by rec** [comment]
[378.txt](https://github.com/ManiacalLabs/BiblioPixel/files/1229364/378.txt)

Let's see if I can directly BP it!

**Comment by adammhaile** [comment]
Why?

**Comment by rec** [comment]
Just to see if I can run BP right off a bug report.  But I discovered two things!

First, you can't attach JSON to a bug report - there's a limited list and that ain't one of them.

Second, somehow that URL fails to load even though it exists when you click on it (though it forces a download).  I get:

    ValueError: Couldn't read 
    https://github.com/ManiacalLabs/BiblioPixel/files/1229364/378.txt with code 404:
    404: Not Found

and that happens if I use `requests` to make the request too!

Lots of education.
