### ISSUE TITLE
We swallow useful exceptions, even with `--verbose`

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#427]
We get tracebacks like this:

    Traceback (most recent call last):
      File "/development/env/bp/bin/bp", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/development/BiblioPixel/scripts/bp", line 15, in <module>
        main.main()
      File "/development/BiblioPixel/bibliopixel/main/main.py", line 62, in main
        return run(args) or 0
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 42, in run
        raise ValueError('Run aborted')
    ValueError: Run aborted

**Comment by rec** [comment]
(See #425)
