### ISSUE TITLE
Better error if someone accidentally installs `serial` instead of `pyserial`.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#526]

**Comment by rec** [comment]
You get this useless error: `'module' object has no attribute 'VERSION'` or in `--verbose`

    Traceback (most recent call last):
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 55, in _get_animations
        animation = common_flags.make_animation(args, desc)
      File "/development/BiblioPixel/bibliopixel/main/common_flags.py", line 178, in make_animation
        return make_project(args, desc).make_animation()
      File "/development/BiblioPixel/bibliopixel/main/common_flags.py", line 174, in make_project
        return project.project(project_flags, desc)
      File "/development/BiblioPixel/bibliopixel/project/project.py", line 50, in project
        return construct.construct(**desc)
      File "/development/BiblioPixel/bibliopixel/project/construct.py", line 13, in construct
        return datatype(*args, **kwds)
      File "/development/BiblioPixel/bibliopixel/project/project.py", line 27, in __init__
        self.drivers = [self.construct_child(**d) for d in drivers]
      File "/development/BiblioPixel/bibliopixel/project/project.py", line 27, in <listcomp>
        self.drivers = [self.construct_child(**d) for d in drivers]
      File "/development/BiblioPixel/bibliopixel/project/project.py", line 16, in construct_child
        return construct(self, **kwds)
      File "/development/BiblioPixel/bibliopixel/drivers/driver_base.py", line 22, in construct
        return cls(maker=project.maker, **desc)
      File "/development/BiblioPixel/bibliopixel/drivers/serial/driver.py", line 28, in __init__
        self.devices = Devices(hardwareID, baudrate)
      File "/development/BiblioPixel/bibliopixel/drivers/serial/devices.py", line 14, in __init__
        self.serial = import_module('serial')
      File "/development/BiblioPixel/bibliopixel/project/importer.py", line 73, in import_module
        return _import(typename, python_path, loader=load.module)
      File "/development/BiblioPixel/bibliopixel/project/importer.py", line 53, in _import
        _validate_typename(typename)
      File "/development/BiblioPixel/bibliopixel/project/importer.py", line 41, in _validate_typename
        version = __import__(root_module).VERSION
    AttributeError: 'module' object has no attribute 'VERSION'
