### ISSUE TITLE
all_pixel_test failing - "the JSON object must be str, not 'dict'"

### ISSUE THREAD

**Issue by haooken** [ManiacalLabs/BiblioPixel#573]
$ bp all_pixel_test WS2812
> ERROR - run - 1 project failed
> ERROR - run - When reading description:
> {}
> encountered exception
> the JSON object must be str, not 'dict'
> 
> the JSON object must be str, not 'dict'
> ERROR: Run aborted

Fresh install of Raspbian Stretch (11-29-2107), fresh install of BP 3.4.2. The above is seen with and without 'sudo'. Also seen with different LED Types (tried 'WS2812' and 'LPD8806'). 'bp all_pixel' appears to work fine, if that means anything.

**Comment by adammhaile** [comment]
@rec - all_pixel_test is only in the code in the list of valid commands.
There's nothing that actually uses it though. I don't remember what it was
ever for :P

**Comment by rec** [comment]
Good catch here!

For future reference - when reporting a bug, please re-run with the -v flag.  This gives copious debugging information.

IIRC, `all_pixel_test` comes from my consolidating all the things that used to be in `scripts/` into `bp`.  I'm fairly certain that I tested this at the time, as I have always had an AllPixel around.  "At the time" is the key phrase in that sentence.

**Comment by rec** [comment]
$ bp all_pixel_test WS2812 -v
    ERROR - run - 1 project failed
    ERROR - run - When reading description:
    {}
    encountered exception
    Traceback (most recent call last):
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 55, in _get_animations
        desc = json.loads(desc, filename)
      File "/development/BiblioPixel/bibliopixel/util/json.py", line 11, in loads
        return json.loads(s)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'dict'


    the JSON object must be str, not 'dict'
    Traceback (most recent call last):
      File "/development/env/bp/bin/bp", line 6, in <module>
        exec(compile(open(__file__).read(), __file__, 'exec'))
      File "/development/BiblioPixel/scripts/bp", line 15, in <module>
        main.main()
      File "/development/BiblioPixel/bibliopixel/main/main.py", line 80, in main
        return run(args) or 0
      File "/development/BiblioPixel/bibliopixel/main/all_pixel_test.py", line 46, in run
        _run.run(args)
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 112, in run
        animations = _get_animations(args)
      File "/development/BiblioPixel/bibliopixel/main/run.py", line 83, in _get_animations
        raise ValueError('Run aborted')
    ValueError: Run aborted
