### ISSUE TITLE
bp upgrade doesn't work...

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#637]
Traceback (most recent call last):
  File "/development/env/bp-clean/bin/bp", line 15, in <module>
    main.main()
  File "/development/env/bp-clean/lib/python3.4/site-packages/bibliopixel/main/main.py", line 70, in main
    return run(args) or 0
  File "/development/env/bp-clean/lib/python3.4/site-packages/bibliopixel/main/update.py", line 13, in run
    with open(os.path.join(root, 'requirements.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/development/env/bp-clean/lib/python3.4/site-packages/requirements.txt'

**Comment by rec** [comment]
I think we should just get rid of this entirely and use `pip install --upgrade` entirely.  In fact, I don't remember why I did this...

**Comment by adammhaile** [comment]
lol... fine with me.

**Comment by rec** [comment]
Hmm, actually I'm going to fix it.  You might want to send this as a command to a remote `bp` for example.
