### ISSUE TITLE
Better reporting of "stuck" serial devices.

### ISSUE THREAD

**Issue by rec** [ManiacalLabs/BiblioPixel#68]
I managed to get the Jumbo 12k into a state where it needed both the power and the USB to be replugged to get it to work.

During this time, BP threw a stack track that isn't so useful to end users (below).

We need to catch this and report it better.  My somewhat lame suggestion for text:

`The serial driver is not responding.  Unplugging and replugging both power and USB for your lighting unit might solve this.`
## 

```
Traceback (most recent call last):
  File "multi.py", line 30, in <module>
    drivers.append(DriverTeensySmartMatrix(width=w, height=h, deviceID=d_order[i]))
  File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 348, in __init__
    super(DriverTeensySmartMatrix, self).__init__(type=LEDTYPE.GENERIC, num=width * height, deviceID=deviceID, hardwareID=hardwareID)
  File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 109, in __init__
    resp = self._connect()
  File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 171, in _connect
    DriverSerial.findSerialDevices(self._hardwareID)
  File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 138, in findSerialDevices
    id = DriverSerial.getDeviceID(port[0])
  File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 281, in getDeviceID
    resp = ord(com.read(1))
TypeError: ord() expected a character, but string of length 0 found
```

**Comment by rec** [comment]
Unfortunately, I can reproduce this every time with my planned dev branch.  :-/

I get this error, which causes the unit to enter the bad state:

    INFO - serial_driver - Using COM Port: /dev/cu.usbmodem1403261, Device ID: 10, Device Ver: 2
    INFO - serial_driver - Using COM Port: /dev/cu.usbmodem2084771, Device ID: 11, Device Ver: 2
    INFO - serial_driver - Using COM Port: /dev/cu.usbmodem2084491, Device ID: 12, Device Ver: 2
    DEBUG - animation - Frame: 22ms / Update Max: 0ms
    DEBUG - animation - Frame: 21ms / Update Max: 91ms
    DEBUG - animation - Frame: 23ms / Update Max: 114ms
    DEBUG - animation - Frame: 54ms / Update Max: 118ms
    WARNING - animation - Frame-time of 83ms set, but took 99ms!
    DEBUG - animation - Frame: 73ms / Update Max: 120ms
    WARNING - animation - Frame-time of 83ms set, but took 142ms!
    ERROR - serial_driver - There was an unknown error communicating with the device.
    ERROR - serial_driver - There was an unknown error communicating with the device.
    Exception in thread Thread-4:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/development/BiblioPixel/bibliopixel/led.py", line 41, in run
        self._driver.receive_colors(*self._data)
      File "/development/BiblioPixel/bibliopixel/drivers/driver_base.py", line 77, in receive_colors
        self._receive_colors(colors, pos)
      File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 297, in _receive_colors
        DriverSerial._comError()
      File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 144, in _comError
        raise IOError(error)
    OSError: There was an unknown error communicating with the device.

    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/development/BiblioPixel/bibliopixel/led.py", line 41, in run
        self._driver.receive_colors(*self._data)
      File "/development/BiblioPixel/bibliopixel/drivers/driver_base.py", line 77, in receive_colors
        self._receive_colors(colors, pos)
      File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 297, in _receive_colors
        DriverSerial._comError()
      File "/development/BiblioPixel/bibliopixel/drivers/serial_driver.py", line 144, in _comError
        raise IOError(error)
    OSError: There was an unknown error communicating with the device.

      ^C ^C^C  ^C ^C^CTraceback (most recent call last):
      File "multi.py", line 57, in <module>
        anim.run(amt=6, fps=12)
      File "/development/BiblioPixel/bibliopixel/animation.py", line 178, in run
        self._run(amt, fps, sleep, max_steps, untilComplete, max_cycles, seconds)
      File "/development/BiblioPixel/bibliopixel/animation.py", line 117, in _run
        self._led.push_to_driver()
      File "/development/BiblioPixel/bibliopixel/led.py", line 181, in push_to_driver
        self._updateThread.setData(data)
      File "/development/BiblioPixel/bibliopixel/led.py", line 68, in setData
        self._reading.wait()
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 552, in wait
        signaled = self._cond.wait(timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 289, in wait
        waiter.acquire()
    KeyboardInterrupt

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "multi.py", line 61, in <module>
        anim.cleanup()
      File "/development/BiblioPixel/bibliopixel/animation.py", line 70, in cleanup
        return self.__exit__(None, None, None)
      File "/development/BiblioPixel/bibliopixel/animation.py", line 66, in __exit__
        self._led.push_to_driver()
      File "/development/BiblioPixel/bibliopixel/led.py", line 181, in push_to_driver
        self._updateThread.setData(data)
      File "/development/BiblioPixel/bibliopixel/led.py", line 68, in setData
        self._reading.wait()
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 552, in wait
        signaled = self._cond.wait(timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 289, in wait
        waiter.acquire()
    KeyboardInterrupt

**Comment by rec** [comment]
I'll work on this when I get the 12k set up - otherwise I can't test this.

**Comment by adammhaile** [comment]
With all the changes lately this doesn't even apply any more
