### ISSUE TITLE
release_test remote fails on Windows

### ISSUE THREAD

**Issue by adammhaile** [ManiacalLabs/BiblioPixel#950]
@rec Not sure what's up here. Am I running the script from the wrong working dir or something?

```
C:\dev\BiblioPixel\BiblioPixel\scripts\release_test (dev -> origin)
(bp3_test) λ python release_test remote
Features: browser keyboard windows
Running tests: tests.remote
tests.remote         running...Open a simpixel browser window and press return.

*** ERROR ***
WARNING - load - This "path" entry does not exist: "C"
Traceback (most recent call last):
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\project\project.py", line 126, in run
    self.start()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\project\project.py", line 94, in start
    self.animation.start()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\animation.py", line 107, in start
    self.threading.start()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\util\threads\animation_threading.py", line 78, in start
    self.target()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\util\threads\animation_threading.py", line 38, in target
    self.run()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\animation.py", line 116, in run_all_frames
    for i in self.generate_frames():
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\animation.py", line 120, in generate_frames
    self._pre_run()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\animation.py", line 179, in _pre_run
    self.pre_run()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\remote\control.py", line 225, in pre_run
    self.server.start()
  File "c:\python\python36-32\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\python\python36-32\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python\python36-32\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\python\python36-32\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\python\python36-32\Lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Envs\bp3_test\Scripts\bp", line 4, in <module>
    __import__('pkg_resources').run_script('BiblioPixel==3.4.18', 'bp')
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\pkg_resources\__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\pkg_resources\__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "c:\users\admin\envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\EGG-INFO\scripts\bp", line 15, in <module>
    main.main()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\main\main.py", line 79, in main
    result = run(args) or 0
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\main\run.py", line 211, in run
    run_once(args)
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\main\run.py", line 197, in run_once
    _run_projects(projects, args)
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\main\run.py", line 168, in _run_projects
    project.run()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\project\project.py", line 129, in run
    self.cleanup()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\project\project.py", line 111, in cleanup
    self.animation.cleanup()
  File "C:\Users\admin\Envs\bp3_test\lib\site-packages\bibliopixel-3.4.18-py3.6.egg\bibliopixel\animation\remote\control.py", line 176, in cleanup
    self.server.terminate()
  File "c:\python\python36-32\Lib\multiprocessing\process.py", line 116, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'


--------------

stdout follows:

--------------
INFO - ScreenGrab - Using PIL ImageGrab module
DEBUG - matrix - Auto generating coordinate map. Use make_matrix_coord_map directly if more control needed.
DEBUG - indexed - RemoteControl: Off
DEBUG - run - Running file C:\dev\BiblioPixel\BiblioPixel\scripts\release_test\projects\remote.yml
INFO - websocket - Starting WebSocket server thread...
DEBUG - animation_threading - Animation starts on main thread

--------------
Traceback (most recent call last):
  File "release_test", line 37, in run_tests
    test.run()
  File "C:\dev\BiblioPixel\BiblioPixel\scripts\release_test\tests\remote.py", line 9, in run
    common.run_project(PROJECT)
  File "C:\dev\BiblioPixel\BiblioPixel\scripts\release_test\common.py", line 35, in run_project
    execute('bp', '-v', *projects)
  File "C:\dev\BiblioPixel\BiblioPixel\scripts\release_test\common.py", line 28, in execute
    sys.exit(po.returncode)
SystemExit: 1
done

```

**Comment by rec** [comment]
Very little has changed in Remote.  Here are the deltas:

https://github.com/ManiacalLabs/BiblioPixel/compare/master...dev#diff-6ebae6885a06016fe9361cb53c15b845


The same exception appears to be something to do with multiprocessing in general on windows;  https://stackoverflow.com/questions/44996626/python-3-multiprocessing-on-windows-module-main-has-no-attribute-spec

**Comment by rec** [comment]
Can we close this now?

**Comment by adammhaile** [comment]
After I finish some more tests

On Aug 31, 2018 2:26 PM, "Tom Swirly" <notifications@github.com> wrote:

Can we close this now?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ManiacalLabs/BiblioPixel/issues/950#issuecomment-417751820>,
or mute the thread
